### ISSUE TITLE
camera_aravis unable to read images

### ISSUE THREAD

**Issue by srirambadri** [strawlab/camera_aravis#4]
Hi,

I'm using Basler aceA2040 camera. I'm able to use pylon to view the image, but when I run the node, then I get an error saying

```

Camera calibration file /home/students/.ros/camera_info/21717060.yaml not found.

Frame error: ARV_BUFFER_STATUS_TIMEOUT
```

I'm using ROS indigo in ubuntu 14.04.4. Can anyone please suggest what I should do to solve this issue?

Link to a question posted in ros answers :[http://answers.ros.org/question/230632/camera_aravis-unable-to-read-images/](url)

**Comment by nzjrs** [comment]
please file this against the active fork

https://github.com/ssafarik/camera_aravis
